name: "Easy Copybara"
description: "An action for transforming and moving code between repositories."
author: "Romain Barissat"
inputs:
  ssh_key:
    description: "SSH public key."
    required: true

  access_token:
    description: "Personal access token with `repo` permissions. Always required on *destination* and required on *SoT* only if the variable `sot_branch` below is left empty."
    required: false

  sot_repo:
    description: "Source repository (Source of Truth)."
    required: false

  sot_branch:
    description: "SoT branch. Leave empty to use your repository's default branch."
    required: false
    default: ""

  destination_repo:
    description: "Destination repository."
    required: false

  destination_branch:
    description: "Destination branch. Leave empty to use the same as your SoT's branch name."
    required: false
    default: ""

  make_root_path:
    description: "Use a sub-path of the source repo as root for the destination repo."
    required: false
    default: ""

  include_files_sot:
    description: "Files to include when pushing from SoT => Destination (comma separated globs)."
    required: false
    default: "**"

  exclude_files_sot:
    description: "Files to exclude when pushing from SoT => Destination (comma separated globs)."
    required: false
    default: ""

  include_files_dest:
    description: "Files to include when pulling from Destination => SoT (comma separated globs)."
    required: false
    default: "**"

  exclude_files_dest:
    description: "Files to exclude when pulling from Destination => SoT (comma separated globs)."
    required: false
    default: ""

  committer:
    description: "Who will commit changes."
    required: false
    default: Github Actions <actions@github.com>

  default_author:
    description: "Default author if the original author can't be used for some reason."
    required: false
    default: Github Actions <actions@github.com>

  custom_config:
    description: "Copybara configuration file to use."
    required: false
    default: ""

  workflow:
    description: "Workflow to execute. Leave empty to auto-detect (init / push / pr)."
    required: false
    default: ""

  copybara_options:
    description: "Use this, if you want to manually specify some command line options (space-separated)."
    required: false
    default: ""

  ssh_known_hosts:
    description: "SSH known hosts file contents, for authenticating with Copybara."
    required: false
    default: ""

  copybara_image:
    description: "Copybara Docker image to run."
    required: false
    default: "olivr/copybara"

  copybara_image_tag:
    description: "Copybara Docker image tag to use."
    required: false
    default: "latest"

  pr_number:
    description: "If you manually specified the 'pr' workflow, you will need to specify the PR number as well."
    required: false
    default: ""

  create_repo:
    description: "If the destination repo doesn't exist, it will be created (subject to enough permissions attached to the access token)."
    required: false
    default: "yes"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "copy"
  color: "purple"
